# GET http://localhost:5000/api/tickets/closed
# Content-Type: application/json


GET http://localhost:5000/api/tickets/15
Content-Type: application/json


# POST http://localhost:5000/api/issue
# Content-Type: application/json



# {
#     "seat_number":15,
#     "passenger":{
#         "name":"nabrina",
#         "sex":"M",
#         "age":"22",
#         "phone":"943308897"
#     }
# }


